# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e926dfe4d5b4ea740b941c6728410917d516bb1dc8652a1182b490e749038b18e86a1676c205382c445d06e2faaf78b14f6a3a0f9b5150bd7f970ac067ab94f7

test:
  secret_key_base: fec9a18ba60729719aa5c4bb7bbb276cdd64499c47ed3b93c776b7b048481c4beb6fbaa6b52dbebbc22727ce1373e363f269944ac1b130cec79ed273607b324c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
